---
name: aputra

services:
  flask:
    image: aputra/flask:0.1.0
    build:
      context: ../flask-app
      dockerfile: ./Dockerfile
    ports:
     - 7070:8080
    environment:
     - APP_VERSION=0.1.0


    